
void wave()
{
  for(i=0;i<=40;i++)
  { 
    LR1.write(lr1-i);
    LR4.write(lr4-i);
    LR7.write(lr7-i);
    LR2.write(lr2-i);
    LR5.write(lr5-i);
    LR8.write(lr8-i);
    delay(5);
  }
  delay(10);
  for(i=0;i<=40;i++)
  { 
    LL1.write(ll1+i);
    LL4.write(ll4+i);
    LL7.write(ll7+i);
    LL2.write(ll2+i);
    LL5.write(ll5+i);
    LL8.write(ll8+i);
    delay(5);
  }
  delay(10);
   for(i=40;i>=0;i--)
  { 
    LR1.write(lr1-i);
    LR4.write(lr4-i);
    LR7.write(lr7-i);
    LR2.write(lr2-i);
    LR5.write(lr5-i);
    LR8.write(lr8-i);
    delay(5);
  }
  delay(10);
    for(i=40;i>=0;i--)
  { 
    LL1.write(ll1+i);
    LL4.write(ll4+i);
    LL7.write(ll7+i);
    LL2.write(ll2+i);
    LL5.write(ll5+i);
    LL8.write(ll8+i);
    delay(5);
  }
  delay(10);
}

